obj-y	+= xenbus.o
obj-$(CONFIG_XEN_BACKEND) += xenbus_be.o

xenbus_be-objs =
xenbus_be-objs += xenbus_backend_client.o

xenbus-objs =
xenbus-objs += xenbus_client.o
xenbus-objs += xenbus_comms.o
xenbus-objs += xenbus_xs.o
xenbus-objs += xenbus_probe.o
xenbus-objs += xenbus_dev.o
