obj-y += cpupool.o
obj-$(CONFIG_SCHED_ARINC653) += arinc653.o
obj-$(CONFIG_SCHED_CREDIT) += credit.o
obj-$(CONFIG_SCHED_CREDIT2) += credit2.o
obj-$(CONFIG_SCHED_RTDS) += rt.o
obj-$(CONFIG_SCHED_NULL) += null.o
obj-y += core.o
