diff -Naur linux-2.6.12/Makefile linux-2.6.12-pdb/Makefile
--- linux-2.6.12/Makefile	2005-08-01 01:21:21.000000000 +0100
+++ linux-2.6.12-pdb/Makefile	2005-08-01 10:28:10.000000000 +0100
@@ -508,7 +508,7 @@
 ifdef CONFIG_CC_OPTIMIZE_FOR_SIZE
 CFLAGS		+= -Os
 else
-CFLAGS		+= -O2
+CFLAGS		+= -O
 endif
 
 #Add align options if CONFIG_CC_* is not equal to 0
