include $(BASEDIR)/Rules.mk

obj-y += domain_page.o
obj-y += entry.o
obj-y += mm.o
obj-y += seg_fixup.o
obj-y += traps.o

obj-$(supervisor_mode_kernel) += supervisor_mode_kernel.o

include $(BASEDIR)/Post.mk
