.TH XENTRACE 8 "11 March 2004" "Xen domain 0 utils"
.SH NAME
xentrace \- capture Xen trace buffer data
.SH SYNOPSIS
.B xentrace
[
.I OPTIONS
] [
.I FILE
]
.SH DESCRIPTION
.B xentrace
is used to dump data from Xen's per-cpu trace buffers.  Records
are dumped in ASCII format, onto the standard output or a \fIFILE\fP
specified on the command line.
Trace records are formatted as follows:
.PP
                    CPU TSC EVENT D1 D2 D3 D4 D5
.PP
Where CPU is the processor number, TSC is the record's timestamp
(the value of the CPU cycle counter), EVENT is the event ID and
D1...D5 are the trace data.

.SS Options
.TP
.B -t, --log-thresh=l
set the threshold number, l, of new records required to trigger a write of
all new records to the output
.TP
.B -s, --poll-sleep=p
set the time, p, (in milliseconds) to sleep between polling the buffers
for new data.

.SH AUTHOR
Mark A. Williamson <mark.a.williamson@intel.com>

.SH "SEE ALSO"
xentrace_cpuinfo(1), xentrace_format(1)
