.TH XENTRACE_FORMAT 1 "11 May 2004" "Xen domain 0 utils"
.SH NAME
xentrace_format \- pretty-print Xen trace data
.SH SYNOPSIS
.B xentrace_format
[
.I DEFS-FILE
]
.SH DESCRIPTION
.B xentrace_format
parses trace data in \fBxentrace\fP binary format from standard input
and reformats it according to the rules in a file of definitions
(\fIDEFS-FILE\fP), printing to standard output.

The rules in \fIDEFS-FILE\fP should have the format shown below:

\fIevent_id\fP \fIwhitespace\fP \fIformat\fP

Each rule should start on a new line.

The format string may include format specifiers, such as:
%(cpu)d, %(tsc)d, %(event)d, %(1)d, %(2)d, %(3)d, %(4)d, %(5)d

[ the `d' format specifier output in decimal, alternatively `x'
  will output in hexadecimal and `o' will output in octal ]

These correspond to the CPU number, event ID, timestamp counter and
the 5 data fields from the trace record.  There should be one such
rule for each type of event to be pretty-printed (events which do not
have formatting rules are ignored).

A sample format file for Xen's predefined trace events is available
in the file tools/xentrace/formats in the Xen source tree.

Depending on your system and the rate at which trace data is produced,
this script may not be able to keep up with the output of
\fBxentrace\fP if it is piped directly.  In these circumstances you
should have \fBxentrace\fP output to a file for processing off-line.

.SH AUTHOR
Mark A. Williamson <mark.a.williamson@intel.com>

.SH "SEE ALSO"
xentrace(8), xentrace_cpusplit(1)
