obj-y += callback.o
obj-y += descriptor-tables.o
obj-y += domain.o
obj-y += emulate.o
obj-$(CONFIG_PV32) += emul-gate-op.o
obj-y += emul-inv-op.o
obj-y += emul-priv-op.o
obj-$(CONFIG_GRANT_TABLE) += grant_table.o
obj-y += hypercall.o
obj-y += iret.o
obj-y += misc-hypercalls.o
obj-y += mm.o
obj-y += ro-page-fault.o
obj-$(CONFIG_PV_SHIM) += shim.o
obj-y += traps.o

obj-bin-y += dom0_build.init.o
obj-bin-y += gpr_switch.o
