AC_DEFUN([AX_SET_FLAGS],
[for cppflag in $PREPEND_INCLUDES
do
    PREPEND_CPPFLAGS="$PREPEND_CPPFLAGS -I$cppflag"
done
for ldflag in $PREPEND_LIB
do
    PREPEND_LDFLAGS="$PREPEND_LDFLAGS -L$ldflag"
done
for cppflag in $APPEND_INCLUDES
do
    APPEND_CPPFLAGS="$APPEND_CPPFLAGS -I$cppflag"
done
for ldflag in $APPEND_LIB
do
    APPEND_LDFLAGS="$APPEND_LDFLAGS -L$ldflag"
done
CPPFLAGS="$PREPEND_CPPFLAGS $CPPFLAGS $APPEND_CPPFLAGS"
LDFLAGS="$PREPEND_LDFLAGS $LDFLAGS $APPEND_LDFLAGS"])

