--- a/src/Makefile.orig	2010-07-19 13:09:06.000000000 +0200
+++ b/src/Makefile	2010-07-19 13:04:11.000000000 +0200
@@ -71,7 +71,8 @@ noargs : blib $(BIN)/NIC $(BIN)/gpxe.dsk
 # If no architecture is specified in Config or on the command-line,
 # use that of the build machine.
 #
-ARCH		?= $(shell uname -m | sed -e s,i[3456789]86,i386,)
+ARCH		?= $(shell uname -m | sed -e s,i[3456789]86,i386, \
+		-e s,i86pc,x86_32, -e s,amd64,x86_64,)
 
 # handle x86_64 like i386, but set -m32 option for 32bit code only
 ifeq ($(ARCH),x86_64)
