include $(BASEDIR)/Rules.mk

obj-y += acpi.o
obj-y += dom0_ops.o
obj-y += domain.o
obj-y += dom_fw.o
obj-y += hpsimserial.o
obj-y += hypercall.o
obj-y += hyperprivop.o
obj-y += idle0_task.o
obj-y += irq.o
obj-y += ivt.o
obj-y += mm_init.o
obj-y += pcdp.o
obj-y += privop.o
obj-y += process.o
obj-y += regionreg.o
obj-y += sn_console.o
obj-y += vcpu.o
obj-y += vhpt.o
obj-y += xenasm.o
obj-y += xenirq.o
obj-y += xenmem.o
obj-y += xenmisc.o
obj-y += xensetup.o
obj-y += xentime.o
obj-y += flushd.o

obj-$(crash_debug) += gdbstub.o

include $(BASEDIR)/Post.mk
