obj-$(CONFIG_X86) += x86/

lib-y += bsearch.o
lib-y += ctors.o
lib-y += ctype.o
lib-y += list-sort.o
lib-y += parse-size.o
lib-y += rbtree.o
lib-y += sort.o
lib-$(CONFIG_X86) += xxhash32.o
lib-$(CONFIG_X86) += xxhash64.o
