obj-$(CONFIG_HAS_VGA) := vga.o
obj-$(CONFIG_HAS_VIDEO) += font_8x14.o
obj-$(CONFIG_HAS_VIDEO) += font_8x16.o
obj-$(CONFIG_HAS_VIDEO) += font_8x8.o
obj-$(CONFIG_HAS_VIDEO) += lfb.o
obj-$(CONFIG_HAS_VGA) += vesa.o
obj-$(CONFIG_HAS_ARM_HDLCD) += arm_hdlcd.o
