#
# Makefile for Xen components
#

obj-y := hypercall.o xenivt.o xenentry.o xensetup.o xenpal.o xenhpski.o \
	 hypervisor.o util.o xencomm.o xcom_hcall.o xcom_mini.o \
	 xcom_privcmd.o mem.o xen_dma.o

obj-$(CONFIG_IA64_GENERIC) += machvec.o
