#!/bin/csh -f

setenv XENROOT `bk root`
rm -rf $XENROOT/fbsdtmp $XENROOT/freebsd-5.3-xenU
mkdir -p $XENROOT/fbsdtmp
cd $XENROOT/fbsdtmp
echo "step 1"
wget ftp://ftp.freebsd.org/pub/FreeBSD/releases/i386/5.3-RELEASE/src/ssys.aa
wget ftp://ftp.freebsd.org/pub/FreeBSD/releases/i386/5.3-RELEASE/src/ssys.ab
wget ftp://ftp.freebsd.org/pub/FreeBSD/releases/i386/5.3-RELEASE/src/ssys.ac
wget ftp://ftp.freebsd.org/pub/FreeBSD/releases/i386/5.3-RELEASE/src/ssys.ad
wget ftp://ftp.freebsd.org/pub/FreeBSD/releases/i386/5.3-RELEASE/src/ssys.ae
wget ftp://ftp.freebsd.org/pub/FreeBSD/releases/i386/5.3-RELEASE/src/ssys.af
wget ftp://ftp.freebsd.org/pub/FreeBSD/releases/i386/5.3-RELEASE/src/ssys.ag
wget ftp://ftp.freebsd.org/pub/FreeBSD/releases/i386/5.3-RELEASE/src/ssys.ah
wget ftp://ftp.freebsd.org/pub/FreeBSD/releases/i386/5.3-RELEASE/src/ssys.ai
wget ftp://ftp.freebsd.org/pub/FreeBSD/releases/i386/5.3-RELEASE/src/ssys.aj
wget ftp://ftp.freebsd.org/pub/FreeBSD/releases/i386/5.3-RELEASE/src/ssys.ak
wget ftp://ftp.freebsd.org/pub/FreeBSD/releases/i386/5.3-RELEASE/src/ssys.al
mkdir -p foo
cat ssys.?? | tar --unlink -xpzf - -C foo/
mkdir -p $XENROOT/freebsd-5.3-xenU
mv foo/sys/* $XENROOT/freebsd-5.3-xenU
cd $XENROOT
rm -rf $XENROOT/fbsdtmp
echo "step 2"
mkdir -p $XENROOT/freebsd-5.3-xenU/i386-xen/include
cd $XENROOT/freebsd-5.3-xenU/i386-xen/include/
foreach file (../../i386/include/*)
	ln -s $file
end 
echo "step 3"
cd $XENROOT/freebsd-5.3-xen-sparse
echo "step 4"
./mkbuildtree ../freebsd-5.3-xenU
echo "step 5"
cd $XENROOT/freebsd-5.3-xenU/i386-xen/include
ln -s $XENROOT/xen/include/public xen-public
echo "done"
