#!/bin/sh

cat >ext2-test.c <<EOF
#include <ext2fs/ext2fs.h>

int main()
{
	ext2fs_open2;
}
EOF

${CC-gcc} -o ext2-test ext2-test.c -lext2fs >/dev/null 2>&1
if [ $? = 0 ]; then
	echo ext2fs-lib
else
	echo ext2fs
fi

rm -f ext2-test ext2-test.c

exit 0
