#!/usr/bin/env python
#  -*- mode: python; -*-
import sys, os.path

from xen.xm import main

print("WARNING: xend/xm is deprecated.")

if not os.path.exists("/tmp/xm-deprecation-long-warning"):
    print("""
xend is deprecated and scheduled for removal. Please migrate to another
toolstack ASAP.

See http://wiki.xen.org/wiki/Choice_of_Toolstacks for information on
other alternatives, including xl which is designed to be a drop in
replacement for xm (http://wiki.xen.org/wiki/XL).
""")
    open("/tmp/xm-deprecation-long-warning", "w").close()

main.main(sys.argv)
