include $(M)/overrides.mk

obj-m := xen-platform-pci.o

EXTRA_CFLAGS += -I$(M)/platform-pci

xen-platform-pci-objs := evtchn.o platform-pci.o gnttab.o xen_support.o features.o

# Can we do better ?
ifeq ($(ARCH),ia64)
  xen-platform-pci-objs += xcom_mini.o xencomm.o
endif
