subdir-y += svm
subdir-y += vmx

obj-y += hvm.o
obj-y += i8254.o
obj-y += instrlen.o
obj-y += intercept.o
obj-y += io.o
obj-y += irq.o
obj-y += platform.o
obj-y += pmtimer.o
obj-y += rtc.o
obj-y += hpet.o
obj-y += vpt.o
obj-y += vioapic.o
obj-y += vlapic.o
obj-y += vpic.o
obj-y += save.o
