include $(BASEDIR)/Rules.mk

subdirs-y += svm
subdirs-y += vmx

obj-y += hvm.o
obj-y += i8259.o
obj-y += intercept.o
obj-y += io.o
obj-y += platform.o
obj-y += vioapic.o
obj-y += vlapic.o

include $(BASEDIR)/Post.mk
