#!/bin/sh

# This script must be called with the following parameters to have
# an entry added to the TPM-to-domain associations table in /etc/xen/vtpm.db
# vtpm-addtodb <dom name> <instance number>

dir=$(dirname "$0")
. "$dir/vtpm-common.sh"

vtpmdb_add_instance $1 $2
