OBJS-y                 += core.o buffer.o
OBJS-$(CONFIG_Linux)   += linux.o
OBJS-$(CONFIG_FreeBSD) += freebsd.o
OBJS-$(CONFIG_SunOS)   += solaris.o
OBJS-$(CONFIG_NetBSD)  += netbsd.o
OBJS-$(CONFIG_MiniOS)  += minios.o
