/* This file is automatically generated.  Do not edit. */
#ifndef _SELINUX_FLASK_H_
#define _SELINUX_FLASK_H_

/*
 * Security object class definitions
 */
#define SECCLASS_XEN                                     1
#define SECCLASS_DOMAIN                                  2
#define SECCLASS_HVM                                     3
#define SECCLASS_MMU                                     4
#define SECCLASS_RESOURCE                                5
#define SECCLASS_SHADOW                                  6
#define SECCLASS_EVENT                                   7
#define SECCLASS_GRANT                                   8
#define SECCLASS_SECURITY                                9

/*
 * Security identifier indices for initial entities
 */
#define SECINITSID_XEN                                  1
#define SECINITSID_DOM0                                 2
#define SECINITSID_DOMIO                                3
#define SECINITSID_DOMXEN                               4
#define SECINITSID_UNLABELED                            5
#define SECINITSID_SECURITY                             6
#define SECINITSID_IOPORT                               7
#define SECINITSID_IOMEM                                8
#define SECINITSID_IRQ                                  9
#define SECINITSID_DEVICE                               10

#define SECINITSID_NUM                                  10

#endif
