/* This file is automatically generated.  Do not edit. */
static char *initial_sid_to_string[] =
{
    "null",
    "xen",
    "dom0",
    "domU",
    "domio",
    "domxen",
    "unlabeled",
    "security",
    "ioport",
    "iomem",
    "pirq",
    "device",
};

