namespace("libxl__")

libxl__qmp_message_type = Enumeration("qmp_message_type", [
    (1, "QMP"),
    (2, "return"),
    (3, "error"),
    (4, "event"),
    (5, "invalid"),
    ])

libxl__device_kind = Enumeration("device_kind", [
    (1, "VIF"),
    (2, "VBD"),
    (3, "QDISK"),
    (4, "PCI"),
    (5, "VFB"),
    (6, "VKBD"),
    (7, "CONSOLE"),
    ])
