#!/bin/bash
# restructure directories to match future drivers/xen plan
# and move aside xen/x86 specific changes
# WARNING!: This directory movement really confuses hg which makes
# it difficult to do development in a directory which is being used
# for building (as all files in mv'd directories are thought by hg
# to have been deleted).  I don't know how to avoid this right now,
# but if someone has a better way, I'm all ears

#eventually asm-xsi-offsets needs to be part of hypervisor.h/hypercall.h
ln -sf ../../../../xen/include/asm-ia64/asm-xsi-offsets.h include/asm-ia64/xen/

