#############################################################################
# (C) 2005 - Rolf Neugebauer - Intel Research Cambridge
#############################################################################
#
#        File: Makefile
#      Author: Rolf Neugebauer (rolf.neugebauer@intel.com)
#        Date: Mar 2005
# 
# Environment: 
#

# invoke:
# make -C /lib/modules/`uname -r`/build SUBDIRS=`pwd` modules_install

obj-m    := perfcntr.o

