include $(BASEDIR)/Rules.mk

subdirs-$(x86_32) += x86_32
subdirs-$(x86_64) += x86_64

obj-y += emulate.o
obj-y += instrlen.o
obj-y += intr.o
obj-y += svm.o
obj-y += vmcb.o

include $(BASEDIR)/Post.mk
