XEN_ROOT := $(CURDIR)/../../..
include $(XEN_ROOT)/tools/Rules.mk

.PHONY: all
all:

.PHONY: install
install:
	$(INSTALL_DIR) -p $(DESTDIR)$(includedir)

.PHONY: uninstall
.uninstall:

.PHONY: clean
clean:
	@:

.PHONY: distclean
distclean: clean
