
ifneq ($(CONFIG_XEN_IA64_DOM0_VP),y)
obj-y   += util.o
endif

obj-y	+= core/
obj-y	+= console/
obj-y	+= evtchn/
#obj-y	+= balloon/
obj-y	+= privcmd/
obj-y	+= blkback/
#obj-y	+= netback/
obj-y	+= blkfront/
obj-y	+= xenbus/
#obj-y	+= netfront/
#obj-$(CONFIG_XEN_PRIVILEGED_GUEST)	+= privcmd/
#obj-$(CONFIG_XEN_BLKDEV_BACKEND)	+= blkback/
#obj-$(CONFIG_XEN_NETDEV_BACKEND)	+= netback/
#obj-$(CONFIG_XEN_BLKDEV_FRONTEND)	+= blkfront/
#obj-$(CONFIG_XEN_NETDEV_FRONTEND)	+= netfront/
#obj-$(CONFIG_XEN_BLKDEV_TAP)    	+= blktap/

