#!/usr/bin/env python
#  -*- mode: python; -*-
#============================================================================
# This library is free software; you can redistribute it and/or
# modify it under the terms of version 2.1 of the GNU Lesser General Public
# License as published by the Free Software Foundation.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#============================================================================
# Copyright (c) 2007 XenSource Inc.
#============================================================================


import commands
import os.path
import pprint
import sys

import xen.xend.sxp as sxp

def main():
    if len(sys.argv) == 1 or sys.argv[1] in ['', '-']:
        s = sxp.parse(sys.stdin)
    else:
        s = sxp.parse(open(sys.argv[1]))

    pprint.pprint(s)

if __name__ == '__main__':
    sys.exit(main())
