#!/usr/bin/env python

#  -*- mode: python; -*-

# Copyright (c) 2005, XenSource Ltd.

import sys

from xen.util import bugtool


if __name__ == "__main__":
    try:
        sys.exit(bugtool.main())
    except KeyboardInterrupt:
        print "\nInterrupted."
        sys.exit(1)
