
default:
	$(MAKE) -C char
	$(MAKE) -C pci
	$(MAKE) -C net
	$(MAKE) -C block
	$(MAKE) -C cdrom
	$(MAKE) -C ide
	$(MAKE) -C scsi

clean:
	$(MAKE) -C char clean
	$(MAKE) -C pci clean
	$(MAKE) -C net clean
	$(MAKE) -C block clean
	$(MAKE) -C cdrom clean
	$(MAKE) -C ide clean
	$(MAKE) -C scsi clean
