obj-y += char/
obj-$(CONFIG_HAS_CPUFREQ) += cpufreq/
obj-$(CONFIG_HAS_PCI) += pci/
obj-$(CONFIG_HAS_VPCI) += vpci/
obj-$(CONFIG_HAS_PASSTHROUGH) += passthrough/
obj-$(CONFIG_ACPI) += acpi/
obj-$(CONFIG_VIDEO) += video/
