#ifndef __HVMLOADER_CONFIG_SEABIOS_H__
#define __HVMLOADER_CONFIG_SEABIOS_H__

#define BIOS_INFO_PHYSICAL_ADDRESS  0x00001000

#define SEABIOS_PHYSICAL_ADDRESS    0x000E0000

#endif /* __HVMLOADER_CONFIG_SEABIOS_H__ */
