#ifndef __HVMLOADER_CONFIG_SEABIOS_H__
#define __HVMLOADER_CONFIG_SEABIOS_H__

#define OPTIONROM_PHYSICAL_ADDRESS  0x000C8000
#define OPTIONROM_PHYSICAL_END      0x000E0000

#define SEABIOS_PHYSICAL_ADDRESS    0x000E0000

#endif /* __HVMLOADER_CONFIG_SEABIOS_H__ */
