include $(BASEDIR)/Rules.mk

obj-y += efi.o
obj-y += entry.o
obj-y += irq_ia64.o
obj-y += mm_contig.o
obj-y += pal.o
obj-y += process-linux-xen.o
obj-y += sal.o
obj-y += setup.o
obj-y += smpboot.o
obj-y += smp.o
obj-y += sort.o
obj-y += time.o
obj-y += tlb.o
obj-y += unaligned.o
obj-y += unwind.o

include $(BASEDIR)/Post.mk
