
obj-y	+= net_driver_util.o
obj-y	+= util.o

obj-y	+= core/
obj-y	+= char/
obj-y	+= console/
obj-y	+= evtchn/
obj-y	+= balloon/
obj-y	+= privcmd/
obj-y	+= xenbus/

obj-$(CONFIG_XEN_BLKDEV_BACKEND)	+= blkback/
obj-$(CONFIG_XEN_NETDEV_BACKEND)	+= netback/
obj-$(CONFIG_XEN_TPMDEV_BACKEND)	+= tpmback/
obj-$(CONFIG_XEN_BLKDEV_FRONTEND)	+= blkfront/
obj-$(CONFIG_XEN_NETDEV_FRONTEND)	+= netfront/
obj-$(CONFIG_XEN_BLKDEV_TAP)    	+= blktap/
obj-$(CONFIG_XEN_TPMDEV_FRONTEND)	+= tpmfront/
obj-$(CONFIG_XEN_PCIDEV_BACKEND)	+= pciback/
obj-$(CONFIG_XEN_PCIDEV_FRONTEND)	+= pcifront/

