#!/bin/bash 

if [ -z "$DEFAULTS_FILE" ] ; then DEFAULTS_FILE=xenctl.xml ; fi
if [ -z "$DEFAULTS_PATH" ] ; then DEFAULTS_PATH=.:/etc:/var/lib/xen ; fi
if [ -z "$QUERY_DEV" ] ; then QUERY_DEV=eth0 ; fi
if [ -z "$IFCONFIG" ] ; then IFCONFIG=/sbin/ifconfig ; fi
if [ -z "$ROUTE" ] ; then ROUTE=/sbin/route ; fi
if [ -z "$JAVA" ] ; then JAVA=java ; fi


ARGS="$XENCTLARGS -DDEFAULTS_FILE=$DEFAULTS_FILE -DDEFAULTS_PATH=$DEFAULTS_PATH"

$JAVA $ARGS -jar $(dirname $0)/xenctl-cmdline.jar $*
