#! /usr/bin/env bash
set -e

check () {
	set +e
	p=`type -p python$v`
	r=$?
	set -e
	if [ $r = 0 ]; then
		echo >&2 "${0##*/}: will use #!$p for python programs"
		printf "%s\n" "$p"
		exit 0
	fi
}

v="$(python -V 2>&1)"
v="${v#* }"
check
v="${v%.*}"
check
echo >&2 'python version not determined, will use env to find python at runtime'
printf "/usr/bin/env python\n"
