subdir-y += mcheck
subdir-y += mtrr

obj-y += amd.o
obj-y += common.o
obj-y += intel.o
obj-y += intel_cacheinfo.o
obj-y += mwait-idle.o

# Keeping around for VIA support (JBeulich)
# obj-$(x86_32) += centaur.o
