obj-y += ebitmap.o
obj-y += hashtab.o
obj-y += symtab.o
obj-y += sidtab.o
obj-y += avtab.o
obj-y += policydb.o
obj-y += services.o
obj-y += conditional.o
obj-y += mls.o

CFLAGS-y += -iquote $(objtree)/xsm/flask/include
CFLAGS-y += -I$(srctree)/xsm/flask/include
