
# cherrypickxen($1 = allobj)
cherrypickxen = $(foreach var, $(1), \
		$(shell o=$(var); \
			c=$${o%.o}-xen.c; \
			s=$${o%.o}-xen.S; \
			oxen=$${o%.o}-xen.o; \
			[ -f $(srctree)/$(src)/$${c} ] || \
			   [ -f $(srctree)/$(src)/$${s} ] \
				&& echo $$oxen \
				|| echo $(var) ) \
	  )
# filterxen($1 = allobj, $2 = noobjs)
filterxen = $(filter-out $(2), $(1))
