#!/bin/bash -ex

test -f /etc/os-release && cat "$_"

$CC --version

# Express the compiler version as an integer.  e.g. GCC 4.9.2 => 0x040902
cc-ver()
{
    $CC -dumpversion | awk -F. '{ printf "0x%02x%02x%02x", $1, $2, $3 }'
}

# random config or default config
if [[ "${RANDCONFIG}" == "y" ]]; then

    # Append job-specific fixed configuration
    if [[ -n "${EXTRA_FIXED_RANDCONFIG}" ]]; then
        echo "${EXTRA_FIXED_RANDCONFIG}" >> xen/tools/kconfig/allrandom.config
    fi

    make -j$(nproc) -C xen KCONFIG_ALLCONFIG=tools/kconfig/allrandom.config randconfig
    hypervisor_only="y"
else
    echo "CONFIG_DEBUG=${debug}" > xen/.config

    if [[ -n "${EXTRA_XEN_CONFIG}" ]]; then
        echo "${EXTRA_XEN_CONFIG}" >> xen/.config
    fi

    make -j$(nproc) -C xen olddefconfig
fi

# Save the config file before building because build failure causes the script
# to exit early -- bash is invoked with -e.
cp xen/.config xen-config

# arm32 only cross-compiles the hypervisor
if [[ "${XEN_TARGET_ARCH}" = "arm32" ]]; then
    hypervisor_only="y"
fi

# build up our configure options
cfgargs=()
cfgargs+=("--enable-docs")

if [[ "${CC}" == "clang"* ]]; then
    # SeaBIOS cannot be built with clang
    cfgargs+=("--with-system-seabios=/usr/share/seabios/bios.bin")
    # iPXE cannot be built with clang
    cfgargs+=("--with-system-ipxe=/usr/lib/ipxe/ipxe.pxe")
    # newlib cannot be built with clang so we cannot build stubdoms
    cfgargs+=("--disable-stubdom")
fi

if ! test -z "$(ldd /bin/ls|grep musl|head -1)"; then
    # disable --disable-werror for QEMUU when building with MUSL
    cfgargs+=("--with-extra-qemuu-configure-args=\"--disable-werror\"")
    # SeaBIOS doesn't build on MUSL systems
    cfgargs+=("--with-system-seabios=/bin/false")
fi

# Qemu requires Python 3.5 or later, and ninja
if ! type python3 || python3 -c "import sys; res = sys.version_info < (3, 5); exit(not(res))" \
        || ! type ninja; then
    cfgargs+=("--with-system-qemu=/bin/false")
fi

# SeaBIOS requires GCC 4.6 or later
if [[ "${CC}" == "gcc" && `cc-ver` -lt 0x040600 ]]; then
    cfgargs+=("--with-system-seabios=/bin/false")
fi

# Directory for the artefacts to be dumped into
mkdir binaries

if [[ "${hypervisor_only}" == "y" ]]; then
    # Xen-only build
    make -j$(nproc) xen

    # Preserve artefacts
    cp xen/xen binaries/xen
else
    # Full build
    ./configure "${cfgargs[@]}"
    make -j$(nproc) dist

    # Preserve artefacts
    # Note: Some smoke tests depending on finding binaries/xen on a full build
    # even though dist/ contains everything, while some containers don't even
    # build Xen
    cp -r dist binaries/
    if [[ -f xen/xen ]] ; then cp xen/xen binaries/xen; fi
fi
