#!/bin/bash
# CHECK-BUILD CHECK-INSTALL

function error {
    echo
    echo "  *** Check for Python version >= 2.2 FAILED"
    exit 1
}

python -V 2>&1 | cut -d ' ' -f 2 | grep -q '^2.[2345]' || error
