#!/bin/sh
# CHECK-BUILD

RC=0

set -e
test -r /usr/include/X11/keysymdef.h || \
test -r /usr/X11R6/include/X11/keysymdef.h || RC=1

if test ${RC} -ne 0; then
	echo
	echo " *** Check for x11 headers FAILED"
fi

exit ${RC}
