#!/bin/sh
# CHECK-BUILD

. ./funcs.sh

if test -z ${PYTHON}; then
	PYTHON=`/usr/bin/env python 2>/dev/null`
fi
has_or_fail ${PYTHON}

${PYTHON} -c '
import os.path, sys
for p in sys.path:
	if os.path.exists(p + "/config/Makefile"):
		sys.exit(0)
sys.exit(1)
' || fail "can't find python devel files"
