#!/bin/sh
# CHECK-BUILD CHECK-INSTALL

if [ ! "$XENFB_TOOLS" = "y" ]
then
    echo -n "unused, "
    exit 0
fi

RC=0

LIBVNCSERVER_CONFIG="$(which libvncserver-config)"
tmpfile=$(mktemp)

if test -z ${LIBVNCSERVER_CONFIG}; then 
    RC=1
else
    ${LIBVNCSERVER_CONFIG} --libs 2>&1 > /dev/null
    RC=$?
fi

if test $RC -ne 0; then
    echo "FAILED"
	echo " *** libvncserver-config is missing. "
    echo " *** Please install libvncserver."
elif ! ld $($LIBVNCSERVER_CONFIG --libs) -o $tmpfile >/dev/null 2>&1; then
    echo "FAILED"
    echo " *** dependency libraries for libvncserver are missing: "
    RC=1
    for i in $(ld $($LIBVNCSERVER_CONFIG --libs) -o $tmpfile 2>&1 >/dev/null); do
        case $i in
        -l*) echo lib${i#-l}
        esac
    done
fi
rm -f $tmpfile

exit $RC
