#!/bin/sh
# CHECK-BUILD CHECK-INSTALL

. ./funcs.sh

if [ ! "$LIBXENAPI_BINDINGS" = "y" ]
then
    echo -n "unused, "
    exit 0
fi

has_or_fail xml2-config
xml2_libs=`xml2-config --libs` || fail "xml2-config --libs failed"
test_link $xml2_libs || fail "dependency libraries for xml2 are missing"
