#!/bin/sh
# CHECK-BUILD

. ./funcs.sh

if [ X${CONFIG_SYSTEM_LIBAIO} != X"y" ] ; then
    exit 0
fi
if ! has_header libaio.h ; then
    fail "can't find libaio headers, install libaio devel package or set CONFIG_SYSTEM_LIBAIO=n"
fi
