#!/bin/bash
# CHECK-INSTALL

function error {
   echo
   echo '  *** Check for the hotplug scripts (hotplug) FAILED'
   exit 1
}
[ -x "$(which udevinfo)" ] && \
  UDEV_VERSION=$(udevinfo -V | sed -e 's/^.*\ \([0-9]\+\)[^0-9]*/\1/')

if [ -n "$UDEV_VERSION" ] && [ $UDEV_VERSION -ge 059 ]; then
  exit 0
fi

which hotplug 1>/dev/null 2>&1 || error
