#!/bin/sh
# CHECK-BUILD CHECK-INSTALL

. ./funcs.sh

if [ "$LIBXENAPI_BINDINGS" != "y" ]; then
	echo -n "unused, "
	exit 0
fi

has_or_fail curl-config
curl_libs=`curl-config --libs` || fail "curl-config --libs failed"
test_link $curl_libs || fail "dependency libraries for curl are missing"
