#!/bin/sh
# CHECK-INSTALL

. ./funcs.sh

if test -z ${PYTHON}; then
	PYTHON=`/usr/bin/env python 2>/dev/null`
fi
has_or_fail ${PYTHON}

${PYTHON} -c 'import xml.dom.minidom' 2>/dev/null || \
fail "can't import xml.dom.minidom"
