

obj-y	+= console/
obj-y	+= evtchn/
obj-y	+= balloon/
obj-y	+= privcmd/
obj-y	+= xenbus/

obj-$(CONFIG_XEN_BLKDEV_BACKEND)	+= blkback/
obj-$(CONFIG_XEN_NETDEV_BACKEND)	+= netback/
obj-$(CONFIG_XEN_BLKDEV_FRONTEND)	+= blkfront/
obj-$(CONFIG_XEN_NETDEV_FRONTEND)	+= netfront/
obj-$(CONFIG_XEN_BLKDEV_TAP)    	+= blktap/

