obj-y += domain.o
obj-y += domctl.o
obj-y += kernel.o
obj-y += memory.o
obj-y += multicall.o
obj-y += sysctl.o
obj-y += xlat.o

# extra dependencies
domctl.o:	../domctl.c
kernel.o:	../kernel.c
multicall.o:	../multicall.c
sysctl.o:	../sysctl.c
