=head1 NAME

xend-config.sxp - Xen daemon configuration file

=head1 SYNOPSIS

/etc/xen/xend-config.sxp

=head1 DESCRIPTION

The xend(1) program requires xend-config.sxp to specify operating
parameters which determine the behavior of the daemon at runtime.

The parameters are specified in S-expression format.  See the example
configuration file in I</etc/xen/xend-config.sxp> for details.

=head1 OPTIONS

The following lists the daemon configuration parameters:

=over 4

=item I<logfile>

The location of the file to record runtime log messages.  Defaults to
I</var/log/xen/xend.log>.

=item I<loglevel>

Filters out messages below the specified level.  Possible values are
DEBUG, INFO, WARNING, ERROR, CRITICAL.  Defaults to I<DEBUG>.

=item I<xend-http-server>

A boolean value that tells xend whether or not to start the http
stream socket management server.  Defaults to I<no>.

=item I<xend-unix-server>

A boolean value that tells xend whether or not to start the unix
domain socket management server.  This is required for the CLI tools
to operate.  Defaults to I<yes>.

=item I<xend-relocation-server>

A boolean value that tells xend whether or not to start the relocation
server.  This is required for cross-machine migrations.  Defaults to
I<no>.

=item I<xend-unix-path>

The location of the unix domain socket the xend-unix-server will use
to communicate with the management tools.  Defaults to
I</var/lib/xend/xend-socket>.

=item I<xend-port>

The port that will be used by the http management server.  Defaults to
I<8000>.

=item I<xend-relocation-port>

The port that will be used by the relocation server.  Defaults to
I<8002>.

=item I<xend-address> 

The address to which the http management server will bind.  Defaults
to I<''> which means "all interfaces".

=item I<xend-relocation-address>

The address to which the relocation server will bind.  Defaults to
I<''> which means "all interfaces".

=item I<console-limit>

The kilobyte buffer limit that will be enforced by the console server.
This limit is set per-domain, and is needed to prevent a single domain
from overwhelming the console server with massive amounts of data.
Defaults to I<1024>.

=item I<network-script>

The name of the script in I</etc/xen/scripts> that will be run to
setup the networking environment.  This can be any name, but in
general is either I<network-bridge> or I<network-route>.

=item I<vif-script>

The name of the script in I</etc/xen/scripts> that will be run to
setup a virtual interface when it is created or destroyed.  This needs
to (in general) work in unison with the I<network-script>.

=item I<dom0-min-mem>

This specifies the minimum number of megabytes that will be reserved
for Domain0.  If this value is positive, Domain0 will be automatically
ballooned down to this limit to make space for new domains.  If this
is set to 0, Domain0 will not be automatically ballooned.

=item I<dom0-cpus>

This specifies the number of CPUs that Domain0 will be allowed to use.
If the value is 0, all available CPUs will be used by Domain0.

=item I<enable-dump>

A boolean value that tells xend whether or not core dumps of guest
domains should be saved when a crash occurs.  Defaults to I<no>.

=item I<external-migration-tool>

The name of an application or script that can handle external device
migration, such as for example virtual TPM migration. An example
script is I</etc/xen/scripts/external-device-migrate>.

=item I<device-create-timeout>

Integer value that tells xend how long it should wait for a new device
to be created. Defaults to I<100>.

=item I<device-destroy-timeout>

Integer value that tells xend how long it should wait for a device to
be destroyed. Defaults to I<100>.

=back

=head1 EXAMPLES

An example configuration with relocation enabled for the local network:

=over 4

 (xend-relocation-server yes)
 (xend-relocation-address 192.0.2.192)
 (network-script network-bridge)
 (vif-script vif-bridge)
 (dom0-min-mem 0)
 (dom0-cpus 0)

=back

=head1 CAVEATS

Note that relocation is currently unsecured and is very dangerous if
left enabled.  No authentication is performed, and very little sanity
checking takes place.  Enable at your own risk.

=head1 SEE ALSO

B<xend>(1)

=head1 AUTHOR

Dan Smith <danms@us.ibm.com>

