obj-y += memcpy.o memmove.o memset.o memchr.o memzero.o
obj-y += findbit.o setbit.o
obj-y += setbit.o clearbit.o changebit.o
obj-y += testsetbit.o testclearbit.o testchangebit.o
obj-y += strchr.o strrchr.o
obj-y += lib1funcs.o lshrdi3.o div64.o
