// DO NOT EDIT.
//
// This file is generated by:
// gengotypes.py ../../libxl/libxl_types.idl
//
package xenlight

type Error int

const (
	ErrorNonspecific                  Error = -1
	ErrorVersion                      Error = -2
	ErrorFail                         Error = -3
	ErrorNi                           Error = -4
	ErrorNomem                        Error = -5
	ErrorInval                        Error = -6
	ErrorBadfail                      Error = -7
	ErrorGuestTimedout                Error = -8
	ErrorTimedout                     Error = -9
	ErrorNoparavirt                   Error = -10
	ErrorNotReady                     Error = -11
	ErrorOseventRegFail               Error = -12
	ErrorBufferfull                   Error = -13
	ErrorUnknownChild                 Error = -14
	ErrorLockFail                     Error = -15
	ErrorJsonConfigEmpty              Error = -16
	ErrorDeviceExists                 Error = -17
	ErrorCheckpointDevopsDoesNotMatch Error = -18
	ErrorCheckpointDeviceNotSupported Error = -19
	ErrorVnumaConfigInvalid           Error = -20
	ErrorDomainNotfound               Error = -21
	ErrorAborted                      Error = -22
	ErrorNotfound                     Error = -23
	ErrorDomainDestroyed              Error = -24
	ErrorFeatureRemoved               Error = -25
	ErrorProtocolErrorQmp             Error = -26
	ErrorUnknownQmpError              Error = -27
	ErrorQmpGenericError              Error = -28
	ErrorQmpCommandNotFound           Error = -29
	ErrorQmpDeviceNotActive           Error = -30
	ErrorQmpDeviceNotFound            Error = -31
	ErrorQemuApi                      Error = -32
)

type DomainType int

const (
	DomainTypeInvalid DomainType = -1
	DomainTypeHvm     DomainType = 1
	DomainTypePv      DomainType = 2
	DomainTypePvh     DomainType = 3
)

type RdmReserveStrategy int

const (
	RdmReserveStrategyIgnore RdmReserveStrategy = 0
	RdmReserveStrategyHost   RdmReserveStrategy = 1
)

type RdmReservePolicy int

const (
	RdmReservePolicyInvalid RdmReservePolicy = -1
	RdmReservePolicyStrict  RdmReservePolicy = 0
	RdmReservePolicyRelaxed RdmReservePolicy = 1
)

type ChannelConnection int

const (
	ChannelConnectionUnknown ChannelConnection = 0
	ChannelConnectionPty     ChannelConnection = 1
	ChannelConnectionSocket  ChannelConnection = 2
)

type DeviceModelVersion int

const (
	DeviceModelVersionUnknown            DeviceModelVersion = 0
	DeviceModelVersionQemuXenTraditional DeviceModelVersion = 1
	DeviceModelVersionQemuXen            DeviceModelVersion = 2
)

type ConsoleType int

const (
	ConsoleTypeUnknown ConsoleType = 0
	ConsoleTypeSerial  ConsoleType = 1
	ConsoleTypePv      ConsoleType = 2
	ConsoleTypeVuart   ConsoleType = 3
)

type DiskFormat int

const (
	DiskFormatUnknown DiskFormat = 0
	DiskFormatQcow    DiskFormat = 1
	DiskFormatQcow2   DiskFormat = 2
	DiskFormatVhd     DiskFormat = 3
	DiskFormatRaw     DiskFormat = 4
	DiskFormatEmpty   DiskFormat = 5
	DiskFormatQed     DiskFormat = 6
)

type DiskBackend int

const (
	DiskBackendUnknown DiskBackend = 0
	DiskBackendPhy     DiskBackend = 1
	DiskBackendTap     DiskBackend = 2
	DiskBackendQdisk   DiskBackend = 3
)

type NicType int

const (
	NicTypeUnknown  NicType = 0
	NicTypeVifIoemu NicType = 1
	NicTypeVif      NicType = 2
)

type ActionOnShutdown int

const (
	ActionOnShutdownDestroy         ActionOnShutdown = 1
	ActionOnShutdownRestart         ActionOnShutdown = 2
	ActionOnShutdownRestartRename   ActionOnShutdown = 3
	ActionOnShutdownPreserve        ActionOnShutdown = 4
	ActionOnShutdownCoredumpDestroy ActionOnShutdown = 5
	ActionOnShutdownCoredumpRestart ActionOnShutdown = 6
	ActionOnShutdownSoftReset       ActionOnShutdown = 7
)

type Trigger int

const (
	TriggerUnknown  Trigger = 0
	TriggerPower    Trigger = 1
	TriggerSleep    Trigger = 2
	TriggerNmi      Trigger = 3
	TriggerInit     Trigger = 4
	TriggerReset    Trigger = 5
	TriggerS3Resume Trigger = 6
)

type TscMode int

const (
	TscModeDefault        TscMode = 0
	TscModeAlwaysEmulate  TscMode = 1
	TscModeNative         TscMode = 2
	TscModeNativeParavirt TscMode = 3
)

type GfxPassthruKind int

const (
	GfxPassthruKindDefault GfxPassthruKind = 0
	GfxPassthruKindIgd     GfxPassthruKind = 1
)

type TimerMode int

const (
	TimerModeUnknown               TimerMode = -1
	TimerModeDelayForMissedTicks   TimerMode = 0
	TimerModeNoDelayForMissedTicks TimerMode = 1
	TimerModeNoMissedTicksPending  TimerMode = 2
	TimerModeOneMissedTickPending  TimerMode = 3
)

type BiosType int

const (
	BiosTypeUnknown BiosType = 0
	BiosTypeRombios BiosType = 1
	BiosTypeSeabios BiosType = 2
	BiosTypeOvmf    BiosType = 3
)

type Scheduler int

const (
	SchedulerUnknown  Scheduler = 0
	SchedulerSedf     Scheduler = 4
	SchedulerCredit   Scheduler = 5
	SchedulerCredit2  Scheduler = 6
	SchedulerArinc653 Scheduler = 7
	SchedulerRtds     Scheduler = 8
	SchedulerNull     Scheduler = 9
)

type ShutdownReason int

const (
	ShutdownReasonUnknown   ShutdownReason = -1
	ShutdownReasonPoweroff  ShutdownReason = 0
	ShutdownReasonReboot    ShutdownReason = 1
	ShutdownReasonSuspend   ShutdownReason = 2
	ShutdownReasonCrash     ShutdownReason = 3
	ShutdownReasonWatchdog  ShutdownReason = 4
	ShutdownReasonSoftReset ShutdownReason = 5
)

type VgaInterfaceType int

const (
	VgaInterfaceTypeUnknown VgaInterfaceType = 0
	VgaInterfaceTypeCirrus  VgaInterfaceType = 1
	VgaInterfaceTypeStd     VgaInterfaceType = 2
	VgaInterfaceTypeNone    VgaInterfaceType = 3
	VgaInterfaceTypeQxl     VgaInterfaceType = 4
)

type VendorDevice int

const (
	VendorDeviceNone      VendorDevice = 0
	VendorDeviceXenserver VendorDevice = 1
)

type ViridianEnlightenment int

const (
	ViridianEnlightenmentBase                ViridianEnlightenment = 0
	ViridianEnlightenmentFreq                ViridianEnlightenment = 1
	ViridianEnlightenmentTimeRefCount        ViridianEnlightenment = 2
	ViridianEnlightenmentReferenceTsc        ViridianEnlightenment = 3
	ViridianEnlightenmentHcallRemoteTlbFlush ViridianEnlightenment = 4
	ViridianEnlightenmentApicAssist          ViridianEnlightenment = 5
	ViridianEnlightenmentCrashCtl            ViridianEnlightenment = 6
	ViridianEnlightenmentSynic               ViridianEnlightenment = 7
	ViridianEnlightenmentStimer              ViridianEnlightenment = 8
	ViridianEnlightenmentHcallIpi            ViridianEnlightenment = 9
)

type Hdtype int

const (
	HdtypeIde  Hdtype = 1
	HdtypeAhci Hdtype = 2
)

type CheckpointedStream int

const (
	CheckpointedStreamNone  CheckpointedStream = 0
	CheckpointedStreamRemus CheckpointedStream = 1
	CheckpointedStreamColo  CheckpointedStream = 2
)

type VuartType int

const (
	VuartTypeUnknown  VuartType = 0
	VuartTypeSbsaUart VuartType = 1
)

type VkbBackend int

const (
	VkbBackendUnknown VkbBackend = 0
	VkbBackendQemu    VkbBackend = 1
	VkbBackendLinux   VkbBackend = 2
)

type Passthrough int

const (
	PassthroughDefault  Passthrough = 0
	PassthroughDisabled Passthrough = 1
	PassthroughEnabled  Passthrough = 2
	PassthroughSyncPt   Passthrough = 3
	PassthroughSharePt  Passthrough = 4
)

type GicVersion int

const (
	GicVersionDefault GicVersion = 0
	GicVersionV2      GicVersion = 32
	GicVersionV3      GicVersion = 48
)

type TeeType int

const (
	TeeTypeNone  TeeType = 0
	TeeTypeOptee TeeType = 1
)

type Altp2MMode int

const (
	Altp2MModeDisabled Altp2MMode = 0
	Altp2MModeMixed    Altp2MMode = 1
	Altp2MModeExternal Altp2MMode = 2
	Altp2MModeLimited  Altp2MMode = 3
)

type UsbctrlType int

const (
	UsbctrlTypeAuto        UsbctrlType = 0
	UsbctrlTypePv          UsbctrlType = 1
	UsbctrlTypeDevicemodel UsbctrlType = 2
	UsbctrlTypeQusb        UsbctrlType = 3
)

type UsbdevType int

const (
	UsbdevTypeHostdev UsbdevType = 1
)

type VsndPcmFormat int

const (
	VsndPcmFormatS8               VsndPcmFormat = 1
	VsndPcmFormatU8               VsndPcmFormat = 2
	VsndPcmFormatS16Le            VsndPcmFormat = 3
	VsndPcmFormatS16Be            VsndPcmFormat = 4
	VsndPcmFormatU16Le            VsndPcmFormat = 5
	VsndPcmFormatU16Be            VsndPcmFormat = 6
	VsndPcmFormatS24Le            VsndPcmFormat = 7
	VsndPcmFormatS24Be            VsndPcmFormat = 8
	VsndPcmFormatU24Le            VsndPcmFormat = 9
	VsndPcmFormatU24Be            VsndPcmFormat = 10
	VsndPcmFormatS32Le            VsndPcmFormat = 11
	VsndPcmFormatS32Be            VsndPcmFormat = 12
	VsndPcmFormatU32Le            VsndPcmFormat = 13
	VsndPcmFormatU32Be            VsndPcmFormat = 14
	VsndPcmFormatF32Le            VsndPcmFormat = 15
	VsndPcmFormatF32Be            VsndPcmFormat = 16
	VsndPcmFormatF64Le            VsndPcmFormat = 17
	VsndPcmFormatF64Be            VsndPcmFormat = 18
	VsndPcmFormatIec958SubframeLe VsndPcmFormat = 19
	VsndPcmFormatIec958SubframeBe VsndPcmFormat = 20
	VsndPcmFormatMuLaw            VsndPcmFormat = 21
	VsndPcmFormatALaw             VsndPcmFormat = 22
	VsndPcmFormatImaAdpcm         VsndPcmFormat = 23
	VsndPcmFormatMpeg             VsndPcmFormat = 24
	VsndPcmFormatGsm              VsndPcmFormat = 25
)

type VsndStreamType int

const (
	VsndStreamTypeP VsndStreamType = 1
	VsndStreamTypeC VsndStreamType = 2
)

type EventType int

const (
	EventTypeDomainShutdown               EventType = 1
	EventTypeDomainDeath                  EventType = 2
	EventTypeDiskEject                    EventType = 3
	EventTypeOperationComplete            EventType = 4
	EventTypeDomainCreateConsoleAvailable EventType = 5
)

type PsrCmtType int

const (
	PsrCmtTypeCacheOccupancy PsrCmtType = 1
	PsrCmtTypeTotalMemCount  PsrCmtType = 2
	PsrCmtTypeLocalMemCount  PsrCmtType = 3
)

type PsrCbmType int

const (
	PsrCbmTypeUnknown   PsrCbmType = 0
	PsrCbmTypeL3Cbm     PsrCbmType = 1
	PsrCbmTypeL3CbmCode PsrCbmType = 2
	PsrCbmTypeL3CbmData PsrCbmType = 3
	PsrCbmTypeL2Cbm     PsrCbmType = 4
	PsrCbmTypeMbaThrtl  PsrCbmType = 5
)

type PsrFeatType int

const (
	PsrFeatTypeCat PsrFeatType = 1
	PsrFeatTypeMba PsrFeatType = 2
)
