obj-$(CONFIG_INTEL_IOMMU) += vtd/
obj-$(CONFIG_AMD_IOMMU) += amd/
obj-$(CONFIG_X86) += x86/
obj-$(CONFIG_ARM) += arm/

obj-y += iommu.o
obj-$(CONFIG_HAS_PCI) += pci.o
obj-$(CONFIG_HAS_DEVICE_TREE) += device_tree.o
obj-$(CONFIG_HAS_PCI) += ats.o
obj-$(CONFIG_HAS_PCI_MSI) += msi.o
