subdir-y += lib

obj-y += entry.o

obj-y += traps.o
obj-y += domain.o
obj-y += vfp.o
obj-y += smpboot.o
obj-y += domctl.o
obj-y += cache.o

obj-$(EARLY_PRINTK) += debug.o
obj-$(CONFIG_HARDEN_BRANCH_PREDICTOR) += bpi.o
